apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.certificateName }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.secretName }}
  issuerRef:
    name: {{ .Values.issuerRefName }}
    kind: ClusterIssuer
  dnsNames:
  - '*.iogdev.nonprod.us.lnrisk.io'
